In [3]:
import  pandas as pd

In [31]:
df=pd.read_csv("world-happiness-report - world-happiness-report.csv")

In [6]:
df.head()

,Country name,year,Life Ladder,Log GDP per capita,Social support,Healthy life expectancy at birth,Freedom to make life choices,Generosity,Perceptions of corruption,Positive affect,Negative affect
0,Afghanistan,2008,3.724,7.370,0.451,50.80,0.718,0.168,0.882,0.518,0.258
1,Afghanistan,2009,4.402,7.540,0.552,51.20,0.679,0.190,0.850,0.584,0.237
2,Afghanistan,2010,4.758,7.647,0.539,51.60,0.600,0.121,0.707,0.618,0.275
3,Afghanistan,2011,3.832,7.620,0.521,51.92,0.496,0.162,0.731,0.611,0.267
4,Afghanistan,2012,3.783,7.705,0.521,52.24,0.531,0.236,0.776,0.710,0.268

In [7]:
df.tail()

,Country name,year,Life Ladder,Log GDP per capita,Social support,Healthy life expectancy at birth,Freedom to make life choices,Generosity,Perceptions of corruption,Positive affect,Negative affect
1944,Zimbabwe,2016,3.735,7.984,0.768,54.4,0.733,-0.095,0.724,0.738,0.209
1945,Zimbabwe,2017,3.638,8.016,0.754,55.0,0.753,-0.098,0.751,0.806,0.224
1946,Zimbabwe,2018,3.616,8.049,0.775,55.6,0.763,-0.068,0.844,0.710,0.212
1947,Zimbabwe,2019,2.694,7.950,0.759,56.2,0.632,-0.064,0.831,0.716,0.235
1948,Zimbabwe,2020,3.160,7.829,0.717,56.8,0.643,-0.009,0.789,0.703,0.346

In [8]:
df.shape

(1949, 11)

In [9]:
df.columns

Index(['Country name', 'year', 'Life Ladder', 'Log GDP per capita',
       'Social support', 'Healthy life expectancy at birth',
       'Freedom to make life choices', 'Generosity',
       'Perceptions of corruption', 'Positive affect', 'Negative affect'],
      dtype='object')

In [11]:
df.sample(8)

,Country name,year,Life Ladder,Log GDP per capita,Social support,Healthy life expectancy at birth,Freedom to make life choices,Generosity,Perceptions of corruption,Positive affect,Negative affect
1896,Vietnam,2008,5.480,8.440,0.805,66.18,0.889,0.201,0.789,0.665,0.218
1548,Slovenia,2010,6.083,10.419,0.917,69.20,0.896,0.029,0.845,0.671,0.295
954,Latvia,2006,4.710,10.032,0.884,63.16,0.641,-0.229,0.937,0.654,0.234
1304,Norway,2015,7.603,11.033,0.947,72.90,0.948,0.257,0.299,0.843,0.209
950,Laos,2017,4.623,8.890,0.707,58.30,0.891,0.073,0.592,0.873,0.344
1012,Lithuania,2017,6.273,10.429,0.926,66.70,0.749,-0.174,0.790,0.608,0.195
719,Hungary,2016,5.449,10.248,0.900,66.80,0.554,-0.187,0.924,0.666,0.243
1623,Sri Lanka,2014,4.268,9.344,0.805,66.50,0.868,0.299,0.791,0.843,0.187

In [6]:
import pandas as pd

In [8]:
df=pd.read_csv("world-happiness-report - world-happiness-report.csv")

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1949 entries, 0 to 1948
Data columns (total 11 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Country name                      1949 non-null   object
 1   year                              1949 non-null   int64
 2   Life Ladder                       1949 non-null   float64
 3   Log GDP per capita                1913 non-null   float64
 4   Social support                    1936 non-null   float64
 5   Healthy life expectancy at birth  1894 non-null   float64
 6   Freedom to make life choices      1917 non-null   float64
 7   Generosity                        1860 non-null   float64
 8   Perceptions of corruption         1839 non-null   float64
 9   Positive affect                   1927 non-null   float64
 10  Negative affect                   1933 non-null   float64
dtypes: float64(9), int64(1), object(1)
memory usage: 167.6+ KB

In [10]:
df.dtypes

Country name                         object
year                                  int64
Life Ladder                         float64
Log GDP per capita                  float64
Social support                      float64
Healthy life expectancy at birth    float64
Freedom to make life choices        float64
Generosity                          float64
Perceptions of corruption           float64
Positive affect                     float64
Negative affect                     float64
dtype: object

In [32]:
df.describe()

,year,Life Ladder,Log GDP per capita,Social support,Healthy life expectancy at birth,Freedom to make life choices,Generosity,Perceptions of corruption,Positive affect,Negative affect
count,1949.000000,1949.000000,1913.000000,1936.000000,1894.000000,1917.000000,1860.000000,1839.000000,1927.000000,1933.000000
mean,2013.216008,5.466705,9.368453,0.812552,63.359374,0.742558,0.000103,0.747125,0.710003,0.268544
std,4.166828,1.115711,1.154084,0.118482,7.510245,0.142093,0.162215,0.186789,0.107100,0.085168
min,2005.000000,2.375000,6.635000,0.290000,32.300000,0.258000,-0.335000,0.035000,0.322000,0.083000
25%,2010.000000,4.640000,8.464000,0.749750,58.685000,0.647000,-0.113000,0.690000,0.625500,0.206000
50%,2013.000000,5.386000,9.460000,0.835500,65.200000,0.763000,-0.025500,0.802000,0.722000,0.258000
75%,2017.000000,6.283000,10.353000,0.905000,68.590000,0.856000,0.091000,0.872000,0.799000,0.320000
max,2020.000000,8.019000,11.648000,0.987000,77.100000,0.985000,0.698000,0.983000,0.944000,0.705000

In [ ]:
df

In [8]:
df.columns=df.columns.str.strip().str.lower().str.replace(" ","_")
df.columns

Index(['country_name', 'year', 'life_ladder', 'log_gdp_per_capita',
       'social_support', 'healthy_life_expectancy_at_birth',
       'freedom_to_make_life_choices', 'generosity',
       'perceptions_of_corruption', 'positive_affect', 'negative_affect'],
      dtype='object')

In [15]:
df

,_c_o_u_n_t_r_y_ _n_a_m_e_,_y_e_a_r_,_l_i_f_e_ _l_a_d_d_e_r_,_l_o_g_ _g_d_p_ _p_e_r_ _c_a_p_i_t_a_,_s_o_c_i_a_l_ _s_u_p_p_o_r_t_,_h_e_a_l_t_h_y_ _l_i_f_e_ _e_x_p_e_c_t_a_n_c_y_ _a_t_ _b_i_r_t_h_,_f_r_e_e_d_o_m_ _t_o_ _m_a_k_e_ _l_i_f_e_ _c_h_o_i_c_e_s_,_g_e_n_e_r_o_s_i_t_y_,_p_e_r_c_e_p_t_i_o_n_s_ _o_f_ _c_o_r_r_u_p_t_i_o_n_,_p_o_s_i_t_i_v_e_ _a_f_f_e_c_t_,_n_e_g_a_t_i_v_e_ _a_f_f_e_c_t_
0,Afghanistan,2008,3.724,7.370,0.451,50.80,0.718,0.168,0.882,0.518,0.258
1,Afghanistan,2009,4.402,7.540,0.552,51.20,0.679,0.190,0.850,0.584,0.237
2,Afghanistan,2010,4.758,7.647,0.539,51.60,0.600,0.121,0.707,0.618,0.275
3,Afghanistan,2011,3.832,7.620,0.521,51.92,0.496,0.162,0.731,0.611,0.267
4,Afghanistan,2012,3.783,7.705,0.521,52.24,0.531,0.236,0.776,0.710,0.268
...,...,...,...,...,...,...,...,...,...,...,...
1944,Zimbabwe,2016,3.735,7.984,0.768,54.40,0.733,-0.095,0.724,0.738,0.209
1945,Zimbabwe,2017,3.638,8.016,0.754,55.00,0.753,-0.098,0.751,0.806,0.224
1946,Zimbabwe,2018,3.616,8.049,0.775,55.60,0.763,-0.068,0.844,0.710,0.212
1947,Zimbabwe,2019,2.694,7.950,0.759,56.20,0.632,-0.064,0.831,0.716,0.235
1948,Zimbabwe,2020,3.160,7.829,0.717,56.80,0.643,-0.009,0.789,0.703,0.346

In [16]:
df.isnull()

,_c_o_u_n_t_r_y_ _n_a_m_e_,_y_e_a_r_,_l_i_f_e_ _l_a_d_d_e_r_,_l_o_g_ _g_d_p_ _p_e_r_ _c_a_p_i_t_a_,_s_o_c_i_a_l_ _s_u_p_p_o_r_t_,_h_e_a_l_t_h_y_ _l_i_f_e_ _e_x_p_e_c_t_a_n_c_y_ _a_t_ _b_i_r_t_h_,_f_r_e_e_d_o_m_ _t_o_ _m_a_k_e_ _l_i_f_e_ _c_h_o_i_c_e_s_,_g_e_n_e_r_o_s_i_t_y_,_p_e_r_c_e_p_t_i_o_n_s_ _o_f_ _c_o_r_r_u_p_t_i_o_n_,_p_o_s_i_t_i_v_e_ _a_f_f_e_c_t_,_n_e_g_a_t_i_v_e_ _a_f_f_e_c_t_
0,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...
1944,False,False,False,False,False,False,False,False,False,False,False
1945,False,False,False,False,False,False,False,False,False,False,False
1946,False,False,False,False,False,False,False,False,False,False,False
1947,False,False,False,False,False,False,False,False,False,False,False
1948,False,False,False,False,False,False,False,False,False,False,False

In [13]:
df.isnull().sum()

Country name                          0
year                                  0
Life Ladder                           0
Log GDP per capita                   36
Social support                       13
Healthy life expectancy at birth     55
Freedom to make life choices         32
Generosity                           89
Perceptions of corruption           110
Positive affect                      22
Negative affect                      16
dtype: int64

In [17]:
df=df.dropna()

In [18]:
df

,_c_o_u_n_t_r_y_ _n_a_m_e_,_y_e_a_r_,_l_i_f_e_ _l_a_d_d_e_r_,_l_o_g_ _g_d_p_ _p_e_r_ _c_a_p_i_t_a_,_s_o_c_i_a_l_ _s_u_p_p_o_r_t_,_h_e_a_l_t_h_y_ _l_i_f_e_ _e_x_p_e_c_t_a_n_c_y_ _a_t_ _b_i_r_t_h_,_f_r_e_e_d_o_m_ _t_o_ _m_a_k_e_ _l_i_f_e_ _c_h_o_i_c_e_s_,_g_e_n_e_r_o_s_i_t_y_,_p_e_r_c_e_p_t_i_o_n_s_ _o_f_ _c_o_r_r_u_p_t_i_o_n_,_p_o_s_i_t_i_v_e_ _a_f_f_e_c_t_,_n_e_g_a_t_i_v_e_ _a_f_f_e_c_t_
0,Afghanistan,2008,3.724,7.370,0.451,50.80,0.718,0.168,0.882,0.518,0.258
1,Afghanistan,2009,4.402,7.540,0.552,51.20,0.679,0.190,0.850,0.584,0.237
2,Afghanistan,2010,4.758,7.647,0.539,51.60,0.600,0.121,0.707,0.618,0.275
3,Afghanistan,2011,3.832,7.620,0.521,51.92,0.496,0.162,0.731,0.611,0.267
4,Afghanistan,2012,3.783,7.705,0.521,52.24,0.531,0.236,0.776,0.710,0.268
...,...,...,...,...,...,...,...,...,...,...,...
1944,Zimbabwe,2016,3.735,7.984,0.768,54.40,0.733,-0.095,0.724,0.738,0.209
1945,Zimbabwe,2017,3.638,8.016,0.754,55.00,0.753,-0.098,0.751,0.806,0.224
1946,Zimbabwe,2018,3.616,8.049,0.775,55.60,0.763,-0.068,0.844,0.710,0.212
1947,Zimbabwe,2019,2.694,7.950,0.759,56.20,0.632,-0.064,0.831,0.716,0.235
1948,Zimbabwe,2020,3.160,7.829,0.717,56.80,0.643,-0.009,0.789,0.703,0.346

In [34]:
important_cols = [
    'life_ladder',
    'log_gdp_per_capita',
    'social_support',
    'healthy_life_expectancy_at_birth',
    'freedom_to_make_life_choices'
]

for col in important_cols:
    df[col] = df[col].fillna(df[col].mean())

In [36]:
df.isnull().sum()

country_name                          0
year                                  0
life_ladder                           0
log_gdp_per_capita                    0
social_support                        0
healthy_life_expectancy_at_birth      0
freedom_to_make_life_choices          0
generosity                           89
perceptions_of_corruption           110
positive_affect                      22
negative_affect                      16
dtype: int64

In [9]:
df['generosity'] = df['generosity'].fillna(df['generosity'].mean())
df['perceptions_of_corruption'] = df['perceptions_of_corruption'].fillna(df['perceptions_of_corruption'].mean())

In [10]:
df=df.dropna()

In [11]:
df

,country_name,year,life_ladder,log_gdp_per_capita,social_support,healthy_life_expectancy_at_birth,freedom_to_make_life_choices,generosity,perceptions_of_corruption,positive_affect,negative_affect
0,Afghanistan,2008,3.724,7.370,0.451,50.80,0.718,0.168,0.882,0.518,0.258
1,Afghanistan,2009,4.402,7.540,0.552,51.20,0.679,0.190,0.850,0.584,0.237
2,Afghanistan,2010,4.758,7.647,0.539,51.60,0.600,0.121,0.707,0.618,0.275
3,Afghanistan,2011,3.832,7.620,0.521,51.92,0.496,0.162,0.731,0.611,0.267
4,Afghanistan,2012,3.783,7.705,0.521,52.24,0.531,0.236,0.776,0.710,0.268
...,...,...,...,...,...,...,...,...,...,...,...
1944,Zimbabwe,2016,3.735,7.984,0.768,54.40,0.733,-0.095,0.724,0.738,0.209
1945,Zimbabwe,2017,3.638,8.016,0.754,55.00,0.753,-0.098,0.751,0.806,0.224
1946,Zimbabwe,2018,3.616,8.049,0.775,55.60,0.763,-0.068,0.844,0.710,0.212
1947,Zimbabwe,2019,2.694,7.950,0.759,56.20,0.632,-0.064,0.831,0.716,0.235
1948,Zimbabwe,2020,3.160,7.829,0.717,56.80,0.643,-0.009,0.789,0.703,0.346

In [6]:
import pandas as pd

In [7]:
df=pd.read_csv("world-happiness-report - world-happiness-report.csv")

In [12]:
df.isnull().sum()

country_name                        0
year                                0
life_ladder                         0
log_gdp_per_capita                  0
social_support                      0
healthy_life_expectancy_at_birth    0
freedom_to_make_life_choices        0
generosity                          0
perceptions_of_corruption           0
positive_affect                     0
negative_affect                     0
dtype: int64

In [13]:
df = df.drop_duplicates()

In [14]:
df.groupby('country_name')['life_ladder'].mean()

country_name
Afghanistan    3.594667
Albania        5.019385
Algeria        5.191800
Angola         4.420250
Argentina      6.310133
                 ...
Venezuela      6.303083
Vietnam        5.358727
Yemen          3.969200
Zambia         4.551714
Zimbabwe       3.882600
Name: life_ladder, Length: 157, dtype: float64

In [15]:
df.groupby('country_name').size()

country_name
Afghanistan    12
Albania        13
Algeria         5
Angola          4
Argentina      15
               ..
Venezuela      12
Vietnam        11
Yemen          10
Zambia         14
Zimbabwe       15
Length: 157, dtype: int64

In [16]:
df.groupby('country_name')['life_ladder'].agg(['mean', 'min', 'max'])

                  mean    min    max
country_name
Afghanistan   3.594667  2.375  4.758
Albania       5.019385  4.511  5.867
Algeria       5.191800  4.745  5.605
Angola        4.420250  3.795  5.589
Argentina     6.310133  5.793  6.776
...                ...    ...    ...
Venezuela     6.303083  4.041  7.478
Vietnam       5.358727  5.023  5.767
Yemen         3.969200  2.983  4.809
Zambia        4.551714  3.307  5.260
Zimbabwe      3.882600  2.694  4.955

[157 rows x 3 columns]

In [17]:

df.groupby(['country_name', 'year'])['life_ladder'].mean().reset_index()

     country_name  year  life_ladder
0     Afghanistan  2008        3.724
1     Afghanistan  2009        4.402
2     Afghanistan  2010        4.758
3     Afghanistan  2011        3.832
4     Afghanistan  2012        3.783
...           ...   ...          ...
1822     Zimbabwe  2016        3.735
1823     Zimbabwe  2017        3.638
1824     Zimbabwe  2018        3.616
1825     Zimbabwe  2019        2.694
1826     Zimbabwe  2020        3.160

[1827 rows x 3 columns]

In [18]:
df.groupby('country_name')['life_ladder'].mean().reset_index()

    country_name  life_ladder
0    Afghanistan     3.594667
1        Albania     5.019385
2        Algeria     5.191800
3         Angola     4.420250
4      Argentina     6.310133
..           ...          ...
152    Venezuela     6.303083
153      Vietnam     5.358727
154        Yemen     3.969200
155       Zambia     4.551714
156     Zimbabwe     3.882600

[157 rows x 2 columns]

In [19]:
df.groupby('year')['life_ladder'].mean().reset_index()

    year  life_ladder
0   2005     6.553478
1   2006     5.238747
2   2007     5.397381
3   2008     5.431924
4   2009     5.454083
5   2010     5.511457
6   2011     5.416878
7   2012     5.449778
8   2013     5.380397
9   2014     5.382892
10  2015     5.406955
11  2016     5.413534
12  2017     5.476525
13  2018     5.532000
14  2019     5.592784
15  2020     5.874349

In [22]:
df.groupby('country_name')[['log_gdp_per_capita','life_ladder']].mean()

              log_gdp_per_capita  life_ladder
country_name
Afghanistan             7.650833     3.594667
Albania                 9.384385     5.019385
Algeria                 9.329400     5.191800
Angola                  8.990000     4.420250
Argentina              10.033800     6.310133
...                          ...          ...
Venezuela               9.480083     6.303083
Vietnam                 8.619273     5.358727
Yemen                   8.102700     3.969200
Zambia                  8.066857     4.551714
Zimbabwe                7.850333     3.882600

[157 rows x 2 columns]

In [21]:
df=df.dropna()